name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

steps:
# Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/celtic-rite-417209/auth', '.' ]
    id: 'Build Docker Image'
    
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/celtic-rite-417209/auth']
    id: 'Push Docker Image'

  # Step 3: Set the Kubernetes context
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['config', 'set', 'context', 'gke_celtic-rite-417209_europe-west3_tickets-dev']
    id: 'Set Kubectl Context'

  # Step 4: Update the Kubernetes deployment with the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/auth-depl', 'tickets-dev=gcr.io/celtic-rite-417209/auth']
    id: 'Update Kubernetes Deployment'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=CLUSTER_NAME'
    
  # Step 5: Verify the deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['rollout', 'status', 'deployment/auth-depl']
    id: 'Verify Deployment'
    
options:
  machineType: 'N1_HIGHCPU_8'
  substitutionOption: ALLOW_LOOSE
